name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: lpodkalicki/avr-toolchain

    steps:
      - uses: actions/checkout@v2

      - name: Install required packages
        run: apk update && apk add git

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/examples/build -S ${{github.workspace}}/examples -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/examples/build --config ${{env.BUILD_TYPE}}

